name: coverage
on: [push]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: "3.10"

        - name: Build
          uses: ./.github/actions/build

        - name: Test
          uses: ./.github/actions/test

        - name: Pytest coverage comment
          uses: MishaKav/pytest-coverage-comment@main
          with:
            pytest-coverage-path: ./pytest-coverage.txt
            junitxml-path: ./pytest.xml
