name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-abcd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build
        uses: ./.github/actions/build

  publish-abcd:
    needs:
      - build-abcd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install poetry
        run: pip install poetry
      - name: Set up dynamic versioning
        run: poetry self add poetry-dynamic-versioning
      - name: Publish
        run: ./publish.sh
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
