name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-abcd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Build
        uses: ./.github/actions/build

  publish-abcd:
    needs:
      - build-abcd
    runs-on: ubuntu-latest
    steps:
      - name: Install poetry
        run: pip install poetry
      - name: Publish
        run: ./publish.sh
