name: quick-test
on:
  push:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Check docker
          run: docker login --username AleksanderWWW --password ${{ secrets.GHCR_TOKEN }} ghcr.io
